
language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  # - make lint
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: frozen-scrubland-30820
  api_key: ${adc5aa02-49b6-4a36-8e49-59f790c72bff}
